name: Metrics (languages)

permissions:
  contents: write   # necesario para commitear el SVG

on:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:
  push:
    paths:
      - README.md

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generar métricas de lenguajes
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: alexsegui10
          template: classic
          base: header, repositories
          config_timezone: Europe/Madrid
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_limit: 8
          plugin_languages_details: bytes-size, percentage
          plugin_languages_colors: github
          output_action: commit
          filename: metrics-langs.svg
